namespace GoogleAppsScript
open System
open System.Text.RegularExpressions
open Fable.Core
open Fable.Import.JS

[<AutoOpen>]
    module JDBC =
        type [<AllowNullLiteral>] Jdbc =
            abstract getCloudSqlConnection: url: string -> JdbcConnection
            abstract getCloudSqlConnection: url: string * info: obj -> JdbcConnection
            abstract getCloudSqlConnection: url: string * userName: string * password: string -> JdbcConnection
            abstract getConnection: url: string -> JdbcConnection
            abstract getConnection: url: string * info: obj -> JdbcConnection
            abstract getConnection: url: string * userName: string * password: string -> JdbcConnection
            abstract newDate: milliseconds: Integer -> JdbcDate
            abstract newTime: milliseconds: Integer -> JdbcTime
            abstract newTimestamp: milliseconds: Integer -> JdbcTimestamp
            abstract parseDate: date: string -> JdbcDate
            abstract parseTime: time: string -> JdbcTime
            abstract parseTimestamp: timestamp: string -> JdbcTimestamp

        and [<AllowNullLiteral>] JdbcArray =
            abstract free: unit -> unit
            abstract getArray: unit -> obj
            abstract getArray: index: Integer * count: Integer -> obj
            abstract getBaseType: unit -> Integer
            abstract getBaseTypeName: unit -> string
            abstract getResultSet: unit -> JdbcResultSet
            abstract getResultSet: index: Integer * count: Integer -> JdbcResultSet

        and [<AllowNullLiteral>] JdbcBlob =
            abstract free: unit -> unit
            abstract getAppsScriptBlob: unit -> Base.Blob
            abstract getAs: contentType: string -> Base.Blob
            abstract getBytes: position: Integer * length: Integer -> ResizeArray<Byte>
            abstract length: unit -> Integer
            abstract position: pattern: ResizeArray<Byte> * start: Integer -> Integer
            abstract position: pattern: JdbcBlob * start: Integer -> Integer
            abstract setBytes: position: Integer * blobSource: Base.BlobSource -> Integer
            abstract setBytes: position: Integer * blobSource: Base.BlobSource * offset: Integer * length: Integer -> Integer
            abstract setBytes: position: Integer * bytes: ResizeArray<Byte> -> Integer
            abstract setBytes: position: Integer * bytes: ResizeArray<Byte> * offset: Integer * length: Integer -> Integer
            abstract truncate: length: Integer -> unit

        and [<AllowNullLiteral>] JdbcCallableStatement =
            abstract addBatch: unit -> unit
            abstract addBatch: sql: string -> unit
            abstract cancel: unit -> unit
            abstract clearBatch: unit -> unit
            abstract clearParameters: unit -> unit
            abstract clearWarnings: unit -> unit
            abstract close: unit -> unit
            abstract execute: unit -> bool
            abstract execute: sql: string -> bool
            abstract execute: sql: string * autoGeneratedKeys: Integer * sql_: string * columnIndexes: ResizeArray<Integer> -> bool
            abstract execute: sql: string * columnNames: ResizeArray<string> -> bool
            abstract executeBatch: unit -> ResizeArray<Integer>
            abstract executeQuery: unit -> JdbcResultSet
            abstract executeQuery: sql: string -> JdbcResultSet
            abstract executeUpdate: unit -> Integer
            abstract executeUpdate: sql: string -> Integer
            abstract executeUpdate: sql: string * autoGeneratedKeys: Integer * sql_: string * columnIndexes: ResizeArray<Integer> -> Integer
            abstract executeUpdate: sql: string * columnNames: ResizeArray<string> -> Integer
            abstract getArray: parameterIndex: Integer -> JdbcArray
            abstract getArray: parameterName: string -> JdbcArray
            abstract getBigDecimal: parameterIndex: Integer -> BigNumber
            abstract getBigDecimal: parameterName: string -> BigNumber
            abstract getBlob: parameterIndex: Integer -> JdbcBlob
            abstract getBlob: parameterName: string -> JdbcBlob
            abstract getBoolean: parameterIndex: Integer -> bool
            abstract getBoolean: parameterName: string -> bool
            abstract getByte: parameterIndex: Integer -> Byte
            abstract getByte: parameterName: string -> Byte
            abstract getBytes: parameterIndex: Integer -> ResizeArray<Byte>
            abstract getBytes: parameterName: string -> ResizeArray<Byte>
            abstract getClob: parameterIndex: Integer -> JdbcClob
            abstract getClob: parameterName: string -> JdbcClob
            abstract getConnection: unit -> JdbcConnection
            abstract getDate: parameterIndex: Integer -> JdbcDate
            abstract getDate: parameterIndex: Integer * timeZone: string -> JdbcDate
            abstract getDate: parameterName: string -> JdbcDate
            abstract getDate: parameterName: string * timeZone: string -> JdbcDate
            abstract getDouble: parameterIndex: Integer -> float
            abstract getDouble: parameterName: string -> float
            abstract getFetchDirection: unit -> Integer
            abstract getFetchSize: unit -> Integer
            abstract getFloat: parameterIndex: Integer -> float
            abstract getFloat: parameterName: string -> float
            abstract getGeneratedKeys: unit -> JdbcResultSet
            abstract getInt: parameterIndex: Integer -> Integer
            abstract getInt: parameterName: string -> Integer
            abstract getLong: parameterIndex: Integer -> Integer
            abstract getLong: parameterName: string -> Integer
            abstract getMaxFieldSize: unit -> Integer
            abstract getMaxRows: unit -> Integer
            abstract getMetaData: unit -> JdbcResultSetMetaData
            abstract getMoreResults: unit -> bool
            abstract getMoreResults: current: Integer -> bool
            abstract getNClob: parameterIndex: Integer -> JdbcClob
            abstract getNClob: parameterName: string -> JdbcClob
            abstract getNString: parameterIndex: Integer -> string
            abstract getNString: parameterName: string -> string
            abstract getObject: parameterIndex: Integer -> obj
            abstract getObject: parameterName: string -> obj
            abstract getParameterMetaData: unit -> JdbcParameterMetaData
            abstract getQueryTimeout: unit -> Integer
            abstract getRef: parameterIndex: Integer -> JdbcRef
            abstract getRef: parameterName: string -> JdbcRef
            abstract getResultSet: unit -> JdbcResultSet
            abstract getResultSetConcurrency: unit -> Integer
            abstract getResultSetHoldability: unit -> Integer
            abstract getResultSetType: unit -> Integer
            abstract getRowId: parameterIndex: Integer -> JdbcRowId
            abstract getRowId: parameterName: string -> JdbcRowId
            abstract getSQLXML: parameterIndex: Integer -> JdbcSQLXML
            abstract getSQLXML: parameterName: string -> JdbcSQLXML
            abstract getShort: parameterIndex: Integer -> Integer
            abstract getShort: parameterName: string -> Integer
            abstract getString: parameterIndex: Integer -> string
            abstract getString: parameterName: string -> string
            abstract getTime: parameterIndex: Integer -> JdbcTime
            abstract getTime: parameterIndex: Integer * timeZone: string -> JdbcTime
            abstract getTime: parameterName: string -> JdbcTime
            abstract getTime: parameterName: string * timeZone: string -> JdbcTime
            abstract getTimestamp: parameterIndex: Integer -> JdbcTimestamp
            abstract getTimestamp: parameterIndex: Integer * timeZone: string -> JdbcTimestamp
            abstract getTimestamp: parameterName: string -> JdbcTimestamp
            abstract getTimestamp: parameterName: string * timeZone: string -> JdbcTimestamp
            abstract getURL: parameterIndex: Integer -> string
            abstract getURL: parameterName: string -> string
            abstract getUpdateCount: unit -> Integer
            abstract getWarnings: unit -> ResizeArray<string>
            abstract isClosed: unit -> bool
            abstract isPoolable: unit -> bool
            abstract registerOutParameter: parameterIndex: Integer * sqlType: Integer -> unit
            abstract registerOutParameter: parameterIndex: Integer * sqlType: Integer * scale: Integer -> unit
            abstract registerOutParameter: parameterIndex: Integer * sqlType: Integer * typeName: string -> unit
            abstract registerOutParameter: parameterName: string * sqlType: Integer -> unit
            abstract registerOutParameter: parameterName: string * sqlType: Integer * scale: Integer -> unit
            abstract registerOutParameter: parameterName: string * sqlType: Integer * typeName: string -> unit
            abstract setArray: parameterIndex: Integer * x: JdbcArray -> unit
            abstract setBigDecimal: parameterIndex: Integer * x: BigNumber -> unit
            abstract setBigDecimal: parameterName: string * x: BigNumber -> unit
            abstract setBlob: parameterIndex: Integer * x: JdbcBlob -> unit
            abstract setBlob: parameterName: string * x: JdbcBlob -> unit
            abstract setBoolean: parameterIndex: Integer * x: bool -> unit
            abstract setBoolean: parameterName: string * x: bool -> unit
            abstract setByte: parameterIndex: Integer * x: Byte -> unit
            abstract setByte: parameterName: string * x: Byte -> unit
            abstract setBytes: parameterIndex: Integer * x: ResizeArray<Byte> -> unit
            abstract setBytes: parameterName: string * x: ResizeArray<Byte> -> unit
            abstract setClob: parameterIndex: Integer * x: JdbcClob -> unit
            abstract setClob: parameterName: string * x: JdbcClob -> unit
            abstract setCursorName: name: string -> unit
            abstract setDate: parameterIndex: Integer * x: JdbcDate -> unit
            abstract setDate: parameterIndex: Integer * x: JdbcDate * timeZone: string -> unit
            abstract setDate: parameterName: string * x: JdbcDate -> unit
            abstract setDate: parameterName: string * x: JdbcDate * timeZone: string -> unit
            abstract setDouble: parameterIndex: Integer * x: float -> unit
            abstract setDouble: parameterName: string * x: float -> unit
            abstract setEscapeProcessing: enable: bool -> unit
            abstract setFetchDirection: direction: Integer -> unit
            abstract setFetchSize: rows: Integer -> unit
            abstract setFloat: parameterIndex: Integer * x: float -> unit
            abstract setFloat: parameterName: string * x: float -> unit
            abstract setInt: parameterIndex: Integer * x: Integer -> unit
            abstract setInt: parameterName: string * x: Integer -> unit
            abstract setLong: parameterIndex: Integer * x: Integer -> unit
            abstract setLong: parameterName: string * x: Integer -> unit
            abstract setMaxFieldSize: max: Integer -> unit
            abstract setMaxRows: max: Integer -> unit
            abstract setNClob: parameterIndex: Integer * x: JdbcClob -> unit
            abstract setNClob: parameterName: string * value: JdbcClob -> unit
            abstract setNString: parameterIndex: Integer * x: string -> unit
            abstract setNString: parameterName: string * value: string -> unit
            abstract setNull: parameterIndex: Integer * sqlType: Integer -> unit
            abstract setNull: parameterIndex: Integer * sqlType: Integer * typeName: string -> unit
            abstract setNull: parameterName: string * sqlType: Integer -> unit
            abstract setNull: parameterName: string * sqlType: Integer * typeName: string -> unit
            abstract setObject: index: Integer * x: obj -> unit
            abstract setObject: parameterIndex: Integer * x: obj * targetSqlType: Integer -> unit
            abstract setObject: parameterIndex: Integer * x: obj * targetSqlType: Integer * scaleOrLength: Integer -> unit
            abstract setObject: parameterName: string * x: obj -> unit
            abstract setObject: parameterName: string * x: obj * targetSqlType: Integer -> unit
            abstract setObject: parameterName: string * x: obj * targetSqlType: Integer * scale: Integer -> unit
            abstract setPoolable: poolable: bool -> unit
            abstract setQueryTimeout: seconds: Integer -> unit
            abstract setRef: parameterIndex: Integer * x: JdbcRef -> unit
            abstract setRowId: parameterIndex: Integer * x: JdbcRowId -> unit
            abstract setRowId: parameterName: string * x: JdbcRowId -> unit
            abstract setSQLXML: parameterIndex: Integer * x: JdbcSQLXML -> unit
            abstract setSQLXML: parameterName: string * xmlObject: JdbcSQLXML -> unit
            abstract setShort: parameterIndex: Integer * x: Integer -> unit
            abstract setShort: parameterName: string * x: Integer -> unit
            abstract setString: parameterIndex: Integer * x: string -> unit
            abstract setString: parameterName: string * x: string -> unit
            abstract setTime: parameterIndex: Integer * x: JdbcTime -> unit
            abstract setTime: parameterIndex: Integer * x: JdbcTime * timeZone: string -> unit
            abstract setTime: parameterName: string * x: JdbcTime -> unit
            abstract setTime: parameterName: string * x: JdbcTime * timeZone: string -> unit
            abstract setTimestamp: parameterIndex: Integer * x: JdbcTimestamp -> unit
            abstract setTimestamp: parameterIndex: Integer * x: JdbcTimestamp * timeZone: string -> unit
            abstract setTimestamp: parameterName: string * x: JdbcTimestamp -> unit
            abstract setTimestamp: parameterName: string * x: JdbcTimestamp * timeZone: string -> unit
            abstract setURL: parameterIndex: Integer * x: string -> unit
            abstract setURL: parameterName: string * ``val``: string -> unit
            abstract wasNull: unit -> bool

        and [<AllowNullLiteral>] JdbcClob =
            abstract free: unit -> unit
            abstract getAppsScriptBlob: unit -> Base.Blob
            abstract getAs: contentType: string -> Base.Blob
            abstract getSubString: position: Integer * length: Integer -> string
            abstract length: unit -> Integer
            abstract position: search: JdbcClob * start: Integer -> Integer
            abstract position: search: string * start: Integer -> Integer
            abstract setString: position: Integer * blobSource: Base.BlobSource -> Integer
            abstract setString: position: Integer * blobSource: Base.BlobSource * offset: Integer * len: Integer -> Integer
            abstract setString: position: Integer * value: string -> Integer
            abstract setString: position: Integer * value: string * offset: Integer * len: Integer -> Integer
            abstract truncate: length: Integer -> unit

        and [<AllowNullLiteral>] JdbcConnection =
            abstract clearWarnings: unit -> unit
            abstract close: unit -> unit
            abstract commit: unit -> unit
            abstract createArrayOf: typeName: string * elements: ResizeArray<obj> -> JdbcArray
            abstract createBlob: unit -> JdbcBlob
            abstract createClob: unit -> JdbcClob
            abstract createNClob: unit -> JdbcClob
            abstract createSQLXML: unit -> JdbcSQLXML
            abstract createStatement: unit -> JdbcStatement
            abstract createStatement: resultSetType: Integer * resultSetConcurrency: Integer -> JdbcStatement
            abstract createStatement: resultSetType: Integer * resultSetConcurrency: Integer * resultSetHoldability: Integer -> JdbcStatement
            abstract createStruct: typeName: string * attributes: ResizeArray<obj> -> JdbcStruct
            abstract getAutoCommit: unit -> bool
            abstract getCatalog: unit -> string
            abstract getHoldability: unit -> Integer
            abstract getMetaData: unit -> JdbcDatabaseMetaData
            abstract getTransactionIsolation: unit -> Integer
            abstract getWarnings: unit -> ResizeArray<string>
            abstract isClosed: unit -> bool
            abstract isReadOnly: unit -> bool
            abstract isValid: timeout: Integer -> bool
            abstract nativeSQL: sql: string -> string
            abstract prepareCall: sql: string -> JdbcCallableStatement
            abstract prepareCall: sql: string * resultSetType: Integer * resultSetConcurrency: Integer -> JdbcCallableStatement
            abstract prepareCall: sql: string * resultSetType: Integer * resultSetConcurrency: Integer * resultSetHoldability: Integer -> JdbcCallableStatement
            abstract prepareStatement: sql: string -> JdbcPreparedStatement
            abstract prepareStatement: sql: string * autoGeneratedKeys: Integer -> JdbcPreparedStatement
            abstract prepareStatement: sql: string * resultSetType: Integer * resultSetConcurrency: Integer -> JdbcPreparedStatement
            abstract prepareStatement: sql: string * resultSetType: Integer * resultSetConcurrency: Integer * resultSetHoldability: Integer -> JdbcPreparedStatement
            abstract prepareStatementByIndex: sql: string * indices: ResizeArray<Integer> -> JdbcPreparedStatement
            abstract prepareStatementByName: sql: string * columnNames: ResizeArray<string> -> JdbcPreparedStatement
            abstract releaseSavepoint: savepoint: JdbcSavepoint -> unit
            abstract rollback: unit -> unit
            abstract rollback: savepoint: JdbcSavepoint -> unit
            abstract setAutoCommit: autoCommit: bool -> unit
            abstract setCatalog: catalog: string -> unit
            abstract setHoldability: holdability: Integer -> unit
            abstract setReadOnly: readOnly: bool -> unit
            abstract setSavepoint: unit -> JdbcSavepoint
            abstract setSavepoint: name: string -> JdbcSavepoint
            abstract setTransactionIsolation: level: Integer -> unit

        and [<AllowNullLiteral>] JdbcDatabaseMetaData =
            abstract allProceduresAreCallable: unit -> bool
            abstract allTablesAreSelectable: unit -> bool
            abstract autoCommitFailureClosesAllResultSets: unit -> bool
            abstract dataDefinitionCausesTransactionCommit: unit -> bool
            abstract dataDefinitionIgnoredInTransactions: unit -> bool
            abstract deletesAreDetected: ``type``: Integer -> bool
            abstract doesMaxRowSizeIncludeBlobs: unit -> bool
            abstract getAttributes: catalog: string * schemaPattern: string * typeNamePattern: string * attributeNamePattern: string -> JdbcResultSet
            abstract getBestRowIdentifier: catalog: string * schema: string * table: string * scope: Integer * nullable: bool -> JdbcResultSet
            abstract getCatalogSeparator: unit -> string
            abstract getCatalogTerm: unit -> string
            abstract getCatalogs: unit -> JdbcResultSet
            abstract getClientInfoProperties: unit -> JdbcResultSet
            abstract getColumnPrivileges: catalog: string * schema: string * table: string * columnNamePattern: string -> JdbcResultSet
            abstract getColumns: catalog: string * schemaPattern: string * tableNamePattern: string * columnNamePattern: string -> JdbcResultSet
            abstract getConnection: unit -> JdbcConnection
            abstract getCrossReference: parentCatalog: string * parentSchema: string * parentTable: string * foreignCatalog: string * foreignSchema: string * foreignTable: string -> JdbcResultSet
            abstract getDatabaseMajorVersion: unit -> Integer
            abstract getDatabaseMinorVersion: unit -> Integer
            abstract getDatabaseProductName: unit -> string
            abstract getDatabaseProductVersion: unit -> string
            abstract getDefaultTransactionIsolation: unit -> Integer
            abstract getDriverMajorVersion: unit -> Integer
            abstract getDriverMinorVersion: unit -> Integer
            abstract getDriverName: unit -> string
            abstract getDriverVersion: unit -> string
            abstract getExportedKeys: catalog: string * schema: string * table: string -> JdbcResultSet
            abstract getExtraNameCharacters: unit -> string
            abstract getFunctionColumns: catalog: string * schemaPattern: string * functionNamePattern: string * columnNamePattern: string -> JdbcResultSet
            abstract getFunctions: catalog: string * schemaPattern: string * functionNamePattern: string -> JdbcResultSet
            abstract getIdentifierQuoteString: unit -> string
            abstract getImportedKeys: catalog: string * schema: string * table: string -> JdbcResultSet
            abstract getIndexInfo: catalog: string * schema: string * table: string * unique: bool * approximate: bool -> JdbcResultSet
            abstract getJDBCMajorVersion: unit -> Integer
            abstract getJDBCMinorVersion: unit -> Integer
            abstract getMaxBinaryLiteralLength: unit -> Integer
            abstract getMaxCatalogNameLength: unit -> Integer
            abstract getMaxCharLiteralLength: unit -> Integer
            abstract getMaxColumnNameLength: unit -> Integer
            abstract getMaxColumnsInGroupBy: unit -> Integer
            abstract getMaxColumnsInIndex: unit -> Integer
            abstract getMaxColumnsInOrderBy: unit -> Integer
            abstract getMaxColumnsInSelect: unit -> Integer
            abstract getMaxColumnsInTable: unit -> Integer
            abstract getMaxConnections: unit -> Integer
            abstract getMaxCursorNameLength: unit -> Integer
            abstract getMaxIndexLength: unit -> Integer
            abstract getMaxProcedureNameLength: unit -> Integer
            abstract getMaxRowSize: unit -> Integer
            abstract getMaxSchemaNameLength: unit -> Integer
            abstract getMaxStatementLength: unit -> Integer
            abstract getMaxStatements: unit -> Integer
            abstract getMaxTableNameLength: unit -> Integer
            abstract getMaxTablesInSelect: unit -> Integer
            abstract getMaxUserNameLength: unit -> Integer
            abstract getNumericFunctions: unit -> string
            abstract getPrimaryKeys: catalog: string * schema: string * table: string -> JdbcResultSet
            abstract getProcedureColumns: catalog: string * schemaPattern: string * procedureNamePattern: string * columnNamePattern: string -> JdbcResultSet
            abstract getProcedureTerm: unit -> string
            abstract getProcedures: catalog: string * schemaPattern: string * procedureNamePattern: string -> JdbcResultSet
            abstract getResultSetHoldability: unit -> Integer
            abstract getRowIdLifetime: unit -> Integer
            abstract getSQLKeywords: unit -> string
            abstract getSQLStateType: unit -> Integer
            abstract getSchemaTerm: unit -> string
            abstract getSchemas: unit -> JdbcResultSet
            abstract getSchemas: catalog: string * schemaPattern: string -> JdbcResultSet
            abstract getSearchStringEscape: unit -> string
            abstract getStringFunctions: unit -> string
            abstract getSuperTables: catalog: string * schemaPattern: string * tableNamePattern: string -> JdbcResultSet
            abstract getSuperTypes: catalog: string * schemaPattern: string * typeNamePattern: string -> JdbcResultSet
            abstract getSystemFunctions: unit -> string
            abstract getTablePrivileges: catalog: string * schemaPattern: string * tableNamePattern: string -> JdbcResultSet
            abstract getTableTypes: unit -> JdbcResultSet
            abstract getTables: catalog: string * schemaPattern: string * tableNamePattern: string * types: ResizeArray<string> -> JdbcResultSet
            abstract getTimeDateFunctions: unit -> string
            abstract getTypeInfo: unit -> JdbcResultSet
            abstract getUDTs: catalog: string * schemaPattern: string * typeNamePattern: string * types: ResizeArray<Integer> -> JdbcResultSet
            abstract getURL: unit -> string
            abstract getUserName: unit -> string
            abstract getVersionColumns: catalog: string * schema: string * table: string -> JdbcResultSet
            abstract insertsAreDetected: ``type``: Integer -> bool
            abstract isCatalogAtStart: unit -> bool
            abstract isReadOnly: unit -> bool
            abstract locatorsUpdateCopy: unit -> bool
            abstract nullPlusNonNullIsNull: unit -> bool
            abstract nullsAreSortedAtEnd: unit -> bool
            abstract nullsAreSortedAtStart: unit -> bool
            abstract nullsAreSortedHigh: unit -> bool
            abstract nullsAreSortedLow: unit -> bool
            abstract othersDeletesAreVisible: ``type``: Integer -> bool
            abstract othersInsertsAreVisible: ``type``: Integer -> bool
            abstract othersUpdatesAreVisible: ``type``: Integer -> bool
            abstract ownDeletesAreVisible: ``type``: Integer -> bool
            abstract ownInsertsAreVisible: ``type``: Integer -> bool
            abstract ownUpdatesAreVisible: ``type``: Integer -> bool
            abstract storesLowerCaseIdentifiers: unit -> bool
            abstract storesLowerCaseQuotedIdentifiers: unit -> bool
            abstract storesMixedCaseIdentifiers: unit -> bool
            abstract storesMixedCaseQuotedIdentifiers: unit -> bool
            abstract storesUpperCaseIdentifiers: unit -> bool
            abstract storesUpperCaseQuotedIdentifiers: unit -> bool
            abstract supportsANSI92EntryLevelSQL: unit -> bool
            abstract supportsANSI92FullSQL: unit -> bool
            abstract supportsANSI92IntermediateSQL: unit -> bool
            abstract supportsAlterTableWithAddColumn: unit -> bool
            abstract supportsAlterTableWithDropColumn: unit -> bool
            abstract supportsBatchUpdates: unit -> bool
            abstract supportsCatalogsInDataManipulation: unit -> bool
            abstract supportsCatalogsInIndexDefinitions: unit -> bool
            abstract supportsCatalogsInPrivilegeDefinitions: unit -> bool
            abstract supportsCatalogsInProcedureCalls: unit -> bool
            abstract supportsCatalogsInTableDefinitions: unit -> bool
            abstract supportsColumnAliasing: unit -> bool
            abstract supportsConvert: unit -> bool
            abstract supportsConvert: fromType: Integer * toType: Integer -> bool
            abstract supportsCoreSQLGrammar: unit -> bool
            abstract supportsCorrelatedSubqueries: unit -> bool
            abstract supportsDataDefinitionAndDataManipulationTransactions: unit -> bool
            abstract supportsDataManipulationTransactionsOnly: unit -> bool
            abstract supportsDifferentTableCorrelationNames: unit -> bool
            abstract supportsExpressionsInOrderBy: unit -> bool
            abstract supportsExtendedSQLGrammar: unit -> bool
            abstract supportsFullOuterJoins: unit -> bool
            abstract supportsGetGeneratedKeys: unit -> bool
            abstract supportsGroupBy: unit -> bool
            abstract supportsGroupByBeyondSelect: unit -> bool
            abstract supportsGroupByUnrelated: unit -> bool
            abstract supportsIntegrityEnhancementFacility: unit -> bool
            abstract supportsLikeEscapeClause: unit -> bool
            abstract supportsLimitedOuterJoins: unit -> bool
            abstract supportsMinimumSQLGrammar: unit -> bool
            abstract supportsMixedCaseIdentifiers: unit -> bool
            abstract supportsMixedCaseQuotedIdentifiers: unit -> bool
            abstract supportsMultipleOpenResults: unit -> bool
            abstract supportsMultipleResultSets: unit -> bool
            abstract supportsMultipleTransactions: unit -> bool
            abstract supportsNamedParameters: unit -> bool
            abstract supportsNonNullableColumns: unit -> bool
            abstract supportsOpenCursorsAcrossCommit: unit -> bool
            abstract supportsOpenCursorsAcrossRollback: unit -> bool
            abstract supportsOpenStatementsAcrossCommit: unit -> bool
            abstract supportsOpenStatementsAcrossRollback: unit -> bool
            abstract supportsOrderByUnrelated: unit -> bool
            abstract supportsOuterJoins: unit -> bool
            abstract supportsPositionedDelete: unit -> bool
            abstract supportsPositionedUpdate: unit -> bool
            abstract supportsResultSetConcurrency: ``type``: Integer * concurrency: Integer -> bool
            abstract supportsResultSetHoldability: holdability: Integer -> bool
            abstract supportsResultSetType: ``type``: Integer -> bool
            abstract supportsSavepoints: unit -> bool
            abstract supportsSchemasInDataManipulation: unit -> bool
            abstract supportsSchemasInIndexDefinitions: unit -> bool
            abstract supportsSchemasInPrivilegeDefinitions: unit -> bool
            abstract supportsSchemasInProcedureCalls: unit -> bool
            abstract supportsSchemasInTableDefinitions: unit -> bool
            abstract supportsSelectForUpdate: unit -> bool
            abstract supportsStatementPooling: unit -> bool
            abstract supportsStoredFunctionsUsingCallSyntax: unit -> bool
            abstract supportsStoredProcedures: unit -> bool
            abstract supportsSubqueriesInComparisons: unit -> bool
            abstract supportsSubqueriesInExists: unit -> bool
            abstract supportsSubqueriesInIns: unit -> bool
            abstract supportsSubqueriesInQuantifieds: unit -> bool
            abstract supportsTableCorrelationNames: unit -> bool
            abstract supportsTransactionIsolationLevel: level: Integer -> bool
            abstract supportsTransactions: unit -> bool
            abstract supportsUnion: unit -> bool
            abstract supportsUnionAll: unit -> bool
            abstract updatesAreDetected: ``type``: Integer -> bool
            abstract usesLocalFilePerTable: unit -> bool
            abstract usesLocalFiles: unit -> bool

        and [<AllowNullLiteral>] JdbcDate =
            abstract after: ``when``: JdbcDate -> bool
            abstract before: ``when``: JdbcDate -> bool
            abstract getDate: unit -> Integer
            abstract getMonth: unit -> Integer
            abstract getTime: unit -> Integer
            abstract getYear: unit -> Integer
            abstract setDate: date: Integer -> unit
            abstract setMonth: month: Integer -> unit
            abstract setTime: milliseconds: Integer -> unit
            abstract setYear: year: Integer -> unit

        and [<AllowNullLiteral>] JdbcParameterMetaData =
            abstract getParameterClassName: param: Integer -> string
            abstract getParameterCount: unit -> Integer
            abstract getParameterMode: param: Integer -> Integer
            abstract getParameterType: param: Integer -> Integer
            abstract getParameterTypeName: param: Integer -> string
            abstract getPrecision: param: Integer -> Integer
            abstract getScale: param: Integer -> Integer
            abstract isNullable: param: Integer -> Integer
            abstract isSigned: param: Integer -> bool

        and [<AllowNullLiteral>] JdbcPreparedStatement =
            abstract addBatch: unit -> unit
            abstract addBatch: sql: string -> unit
            abstract cancel: unit -> unit
            abstract clearBatch: unit -> unit
            abstract clearParameters: unit -> unit
            abstract clearWarnings: unit -> unit
            abstract close: unit -> unit
            abstract execute: unit -> bool
            abstract execute: sql: string -> bool
            abstract execute: sql: string * autoGeneratedKeys: Integer * sql_: string * columnIndexes: ResizeArray<Integer> -> bool
            abstract execute: sql: string * columnNames: ResizeArray<string> -> bool
            abstract executeBatch: unit -> ResizeArray<Integer>
            abstract executeQuery: unit -> JdbcResultSet
            abstract executeQuery: sql: string -> JdbcResultSet
            abstract executeUpdate: unit -> Integer
            abstract executeUpdate: sql: string -> Integer
            abstract executeUpdate: sql: string * autoGeneratedKeys: Integer * sql_: string * columnIndexes: ResizeArray<Integer> -> Integer
            abstract executeUpdate: sql: string * columnNames: ResizeArray<string> -> Integer
            abstract getConnection: unit -> JdbcConnection
            abstract getFetchDirection: unit -> Integer
            abstract getFetchSize: unit -> Integer
            abstract getGeneratedKeys: unit -> JdbcResultSet
            abstract getMaxFieldSize: unit -> Integer
            abstract getMaxRows: unit -> Integer
            abstract getMetaData: unit -> JdbcResultSetMetaData
            abstract getMoreResults: unit -> bool
            abstract getMoreResults: current: Integer -> bool
            abstract getParameterMetaData: unit -> JdbcParameterMetaData
            abstract getQueryTimeout: unit -> Integer
            abstract getResultSet: unit -> JdbcResultSet
            abstract getResultSetConcurrency: unit -> Integer
            abstract getResultSetHoldability: unit -> Integer
            abstract getResultSetType: unit -> Integer
            abstract getUpdateCount: unit -> Integer
            abstract getWarnings: unit -> ResizeArray<string>
            abstract isClosed: unit -> bool
            abstract isPoolable: unit -> bool
            abstract setArray: parameterIndex: Integer * x: JdbcArray -> unit
            abstract setBigDecimal: parameterIndex: Integer * x: BigNumber -> unit
            abstract setBlob: parameterIndex: Integer * x: JdbcBlob -> unit
            abstract setBoolean: parameterIndex: Integer * x: bool -> unit
            abstract setByte: parameterIndex: Integer * x: Byte -> unit
            abstract setBytes: parameterIndex: Integer * x: ResizeArray<Byte> -> unit
            abstract setClob: parameterIndex: Integer * x: JdbcClob -> unit
            abstract setCursorName: name: string -> unit
            abstract setDate: parameterIndex: Integer * x: JdbcDate -> unit
            abstract setDate: parameterIndex: Integer * x: JdbcDate * timeZone: string -> unit
            abstract setDouble: parameterIndex: Integer * x: float -> unit
            abstract setEscapeProcessing: enable: bool -> unit
            abstract setFetchDirection: direction: Integer -> unit
            abstract setFetchSize: rows: Integer -> unit
            abstract setFloat: parameterIndex: Integer * x: float -> unit
            abstract setInt: parameterIndex: Integer * x: Integer -> unit
            abstract setLong: parameterIndex: Integer * x: Integer -> unit
            abstract setMaxFieldSize: max: Integer -> unit
            abstract setMaxRows: max: Integer -> unit
            abstract setNClob: parameterIndex: Integer * x: JdbcClob -> unit
            abstract setNString: parameterIndex: Integer * x: string -> unit
            abstract setNull: parameterIndex: Integer * sqlType: Integer -> unit
            abstract setNull: parameterIndex: Integer * sqlType: Integer * typeName: string -> unit
            abstract setObject: index: Integer * x: obj -> unit
            abstract setObject: parameterIndex: Integer * x: obj * targetSqlType: Integer -> unit
            abstract setObject: parameterIndex: Integer * x: obj * targetSqlType: Integer * scaleOrLength: Integer -> unit
            abstract setPoolable: poolable: bool -> unit
            abstract setQueryTimeout: seconds: Integer -> unit
            abstract setRef: parameterIndex: Integer * x: JdbcRef -> unit
            abstract setRowId: parameterIndex: Integer * x: JdbcRowId -> unit
            abstract setSQLXML: parameterIndex: Integer * x: JdbcSQLXML -> unit
            abstract setShort: parameterIndex: Integer * x: Integer -> unit
            abstract setString: parameterIndex: Integer * x: string -> unit
            abstract setTime: parameterIndex: Integer * x: JdbcTime -> unit
            abstract setTime: parameterIndex: Integer * x: JdbcTime * timeZone: string -> unit
            abstract setTimestamp: parameterIndex: Integer * x: JdbcTimestamp -> unit
            abstract setTimestamp: parameterIndex: Integer * x: JdbcTimestamp * timeZone: string -> unit
            abstract setURL: parameterIndex: Integer * x: string -> unit

        and [<AllowNullLiteral>] JdbcRef =
            abstract getBaseTypeName: unit -> string
            abstract getObject: unit -> obj
            abstract setObject: ``object``: obj -> unit

        and [<AllowNullLiteral>] JdbcResultSet =
            abstract absolute: row: Integer -> bool
            abstract afterLast: unit -> unit
            abstract beforeFirst: unit -> unit
            abstract cancelRowUpdates: unit -> unit
            abstract clearWarnings: unit -> unit
            abstract close: unit -> unit
            abstract deleteRow: unit -> unit
            abstract findColumn: columnLabel: string -> Integer
            abstract first: unit -> bool
            abstract getArray: columnIndex: Integer -> JdbcArray
            abstract getArray: columnLabel: string -> JdbcArray
            abstract getBigDecimal: columnIndex: Integer -> BigNumber
            abstract getBigDecimal: columnLabel: string -> BigNumber
            abstract getBlob: columnIndex: Integer -> JdbcBlob
            abstract getBlob: columnLabel: string -> JdbcBlob
            abstract getBoolean: columnIndex: Integer -> bool
            abstract getBoolean: columnLabel: string -> bool
            abstract getByte: columnIndex: Integer -> Byte
            abstract getByte: columnLabel: string -> Byte
            abstract getBytes: columnIndex: Integer -> ResizeArray<Byte>
            abstract getBytes: columnLabel: string -> ResizeArray<Byte>
            abstract getClob: columnIndex: Integer -> JdbcClob
            abstract getClob: columnLabel: string -> JdbcClob
            abstract getConcurrency: unit -> Integer
            abstract getCursorName: unit -> string
            abstract getDate: columnIndex: Integer -> JdbcDate
            abstract getDate: columnIndex: Integer * timeZone: string -> JdbcDate
            abstract getDate: columnLabel: string -> JdbcDate
            abstract getDate: columnLabel: string * timeZone: string -> JdbcDate
            abstract getDouble: columnIndex: Integer -> float
            abstract getDouble: columnLabel: string -> float
            abstract getFetchDirection: unit -> Integer
            abstract getFetchSize: unit -> Integer
            abstract getFloat: columnIndex: Integer -> float
            abstract getFloat: columnLabel: string -> float
            abstract getHoldability: unit -> Integer
            abstract getInt: columnIndex: Integer -> Integer
            abstract getInt: columnLabel: string -> Integer
            abstract getLong: columnIndex: Integer -> Integer
            abstract getLong: columnLabel: string -> Integer
            abstract getMetaData: unit -> JdbcResultSetMetaData
            abstract getNClob: columnIndex: Integer -> JdbcClob
            abstract getNClob: columnLabel: string -> JdbcClob
            abstract getNString: columnIndex: Integer -> string
            abstract getNString: columnLabel: string -> string
            abstract getObject: columnIndex: Integer -> obj
            abstract getObject: columnLabel: string -> obj
            abstract getRef: columnIndex: Integer -> JdbcRef
            abstract getRef: columnLabel: string -> JdbcRef
            abstract getRow: unit -> Integer
            abstract getRowId: columnIndex: Integer -> JdbcRowId
            abstract getRowId: columnLabel: string -> JdbcRowId
            abstract getSQLXML: columnIndex: Integer -> JdbcSQLXML
            abstract getSQLXML: columnLabel: string -> JdbcSQLXML
            abstract getShort: columnIndex: Integer -> Integer
            abstract getShort: columnLabel: string -> Integer
            abstract getStatement: unit -> JdbcStatement
            abstract getString: columnIndex: Integer -> string
            abstract getString: columnLabel: string -> string
            abstract getTime: columnIndex: Integer -> JdbcTime
            abstract getTime: columnIndex: Integer * timeZone: string -> JdbcTime
            abstract getTime: columnLabel: string -> JdbcTime
            abstract getTime: columnLabel: string * timeZone: string -> JdbcTime
            abstract getTimestamp: columnIndex: Integer -> JdbcTimestamp
            abstract getTimestamp: columnIndex: Integer * timeZone: string -> JdbcTimestamp
            abstract getTimestamp: columnLabel: string -> JdbcTimestamp
            abstract getTimestamp: columnLabel: string * timeZone: string -> JdbcTimestamp
            abstract getType: unit -> Integer
            abstract getURL: columnIndex: Integer -> string
            abstract getURL: columnLabel: string -> string
            abstract getWarnings: unit -> ResizeArray<string>
            abstract insertRow: unit -> unit
            abstract isAfterLast: unit -> bool
            abstract isBeforeFirst: unit -> bool
            abstract isClosed: unit -> bool
            abstract isFirst: unit -> bool
            abstract isLast: unit -> bool
            abstract last: unit -> bool
            abstract moveToCurrentRow: unit -> unit
            abstract moveToInsertRow: unit -> unit
            abstract next: unit -> bool
            abstract previous: unit -> bool
            abstract refreshRow: unit -> unit
            abstract relative: rows: Integer -> bool
            abstract rowDeleted: unit -> bool
            abstract rowInserted: unit -> bool
            abstract rowUpdated: unit -> bool
            abstract setFetchDirection: direction: Integer -> unit
            abstract setFetchSize: rows: Integer -> unit
            abstract updateArray: columnIndex: Integer * x: JdbcArray -> unit
            abstract updateArray: columnLabel: string * x: JdbcArray -> unit
            abstract updateBigDecimal: columnIndex: Integer * x: BigNumber -> unit
            abstract updateBigDecimal: columnLabel: string * x: BigNumber -> unit
            abstract updateBlob: columnIndex: Integer * x: JdbcBlob -> unit
            abstract updateBlob: columnLabel: string * x: JdbcBlob -> unit
            abstract updateBoolean: columnIndex: Integer * x: bool -> unit
            abstract updateBoolean: columnLabel: string * x: bool -> unit
            abstract updateByte: columnIndex: Integer * x: Byte -> unit
            abstract updateByte: columnLabel: string * x: Byte -> unit
            abstract updateBytes: columnIndex: Integer * x: ResizeArray<Byte> -> unit
            abstract updateBytes: columnLabel: string * x: ResizeArray<Byte> -> unit
            abstract updateClob: columnIndex: Integer * x: JdbcClob -> unit
            abstract updateClob: columnLabel: string * x: JdbcClob -> unit
            abstract updateDate: columnIndex: Integer * x: JdbcDate -> unit
            abstract updateDate: columnLabel: string * x: JdbcDate -> unit
            abstract updateDouble: columnIndex: Integer * x: float -> unit
            abstract updateDouble: columnLabel: string * x: float -> unit
            abstract updateFloat: columnIndex: Integer * x: float -> unit
            abstract updateFloat: columnLabel: string * x: float -> unit
            abstract updateInt: columnIndex: Integer * x: Integer -> unit
            abstract updateInt: columnLabel: string * x: Integer -> unit
            abstract updateLong: columnIndex: Integer * x: Integer -> unit
            abstract updateLong: columnLabel: string * x: Integer -> unit
            abstract updateNClob: columnIndex: Integer * x: JdbcClob -> unit
            abstract updateNClob: columnLabel: string * x: JdbcClob -> unit
            abstract updateNString: columnIndex: Integer * x: string -> unit
            abstract updateNString: columnLabel: string * x: string -> unit
            abstract updateNull: columnIndex: Integer -> unit
            abstract updateNull: columnLabel: string -> unit
            abstract updateObject: columnIndex: Integer * x: obj -> unit
            abstract updateObject: columnIndex: Integer * x: obj * scaleOrLength: Integer -> unit
            abstract updateObject: columnLabel: string * x: obj -> unit
            abstract updateObject: columnLabel: string * x: obj * scaleOrLength: Integer -> unit
            abstract updateRef: columnIndex: Integer * x: JdbcRef -> unit
            abstract updateRef: columnLabel: string * x: JdbcRef -> unit
            abstract updateRow: unit -> unit
            abstract updateRowId: columnIndex: Integer * x: JdbcRowId -> unit
            abstract updateRowId: columnLabel: string * x: JdbcRowId -> unit
            abstract updateSQLXML: columnIndex: Integer * x: JdbcSQLXML -> unit
            abstract updateSQLXML: columnLabel: string * x: JdbcSQLXML -> unit
            abstract updateShort: columnIndex: Integer * x: Integer -> unit
            abstract updateShort: columnLabel: string * x: Integer -> unit
            abstract updateString: columnIndex: Integer * x: string -> unit
            abstract updateString: columnLabel: string * x: string -> unit
            abstract updateTime: columnIndex: Integer * x: JdbcTime -> unit
            abstract updateTime: columnLabel: string * x: JdbcTime -> unit
            abstract updateTimestamp: columnIndex: Integer * x: JdbcTimestamp -> unit
            abstract updateTimestamp: columnLabel: string * x: JdbcTimestamp -> unit
            abstract wasNull: unit -> bool

        and [<AllowNullLiteral>] JdbcResultSetMetaData =
            abstract getCatalogName: column: Integer -> string
            abstract getColumnClassName: column: Integer -> string
            abstract getColumnCount: unit -> Integer
            abstract getColumnDisplaySize: column: Integer -> Integer
            abstract getColumnLabel: column: Integer -> string
            abstract getColumnName: column: Integer -> string
            abstract getColumnType: column: Integer -> Integer
            abstract getColumnTypeName: column: Integer -> string
            abstract getPrecision: column: Integer -> Integer
            abstract getScale: column: Integer -> Integer
            abstract getSchemaName: column: Integer -> string
            abstract getTableName: column: Integer -> string
            abstract isAutoIncrement: column: Integer -> bool
            abstract isCaseSensitive: column: Integer -> bool
            abstract isCurrency: column: Integer -> bool
            abstract isDefinitelyWritable: column: Integer -> bool
            abstract isNullable: column: Integer -> Integer
            abstract isReadOnly: column: Integer -> bool
            abstract isSearchable: column: Integer -> bool
            abstract isSigned: column: Integer -> bool
            abstract isWritable: column: Integer -> bool

        and [<AllowNullLiteral>] JdbcRowId =
            abstract getBytes: unit -> ResizeArray<Byte>

        and [<AllowNullLiteral>] JdbcSQLXML =
            abstract free: unit -> unit
            abstract getString: unit -> string
            abstract setString: value: string -> unit

        and [<AllowNullLiteral>] JdbcSavepoint =
            abstract getSavepointId: unit -> Integer
            abstract getSavepointName: unit -> string

        and [<AllowNullLiteral>] JdbcStatement =
            abstract addBatch: sql: string -> unit
            abstract cancel: unit -> unit
            abstract clearBatch: unit -> unit
            abstract clearWarnings: unit -> unit
            abstract close: unit -> unit
            abstract execute: sql: string -> bool
            abstract execute: sql: string * autoGeneratedKeys: Integer * sql_: string * columnIndexes: ResizeArray<Integer> -> bool
            abstract execute: sql: string * columnNames: ResizeArray<string> -> bool
            abstract executeBatch: unit -> ResizeArray<Integer>
            abstract executeQuery: sql: string -> JdbcResultSet
            abstract executeUpdate: sql: string -> Integer
            abstract executeUpdate: sql: string * autoGeneratedKeys: Integer * sql_: string * columnIndexes: ResizeArray<Integer> -> Integer
            abstract executeUpdate: sql: string * columnNames: ResizeArray<string> -> Integer
            abstract getConnection: unit -> JdbcConnection
            abstract getFetchDirection: unit -> Integer
            abstract getFetchSize: unit -> Integer
            abstract getGeneratedKeys: unit -> JdbcResultSet
            abstract getMaxFieldSize: unit -> Integer
            abstract getMaxRows: unit -> Integer
            abstract getMoreResults: unit -> bool
            abstract getMoreResults: current: Integer -> bool
            abstract getQueryTimeout: unit -> Integer
            abstract getResultSet: unit -> JdbcResultSet
            abstract getResultSetConcurrency: unit -> Integer
            abstract getResultSetHoldability: unit -> Integer
            abstract getResultSetType: unit -> Integer
            abstract getUpdateCount: unit -> Integer
            abstract getWarnings: unit -> ResizeArray<string>
            abstract isClosed: unit -> bool
            abstract isPoolable: unit -> bool
            abstract setCursorName: name: string -> unit
            abstract setEscapeProcessing: enable: bool -> unit
            abstract setFetchDirection: direction: Integer -> unit
            abstract setFetchSize: rows: Integer -> unit
            abstract setMaxFieldSize: max: Integer -> unit
            abstract setMaxRows: max: Integer -> unit
            abstract setPoolable: poolable: bool -> unit
            abstract setQueryTimeout: seconds: Integer -> unit

        and [<AllowNullLiteral>] JdbcStruct =
            abstract getAttributes: unit -> ResizeArray<obj>
            abstract getSQLTypeName: unit -> string

        and [<AllowNullLiteral>] JdbcTime =
            abstract after: ``when``: JdbcTime -> bool
            abstract before: ``when``: JdbcTime -> bool
            abstract getHours: unit -> Integer
            abstract getMinutes: unit -> Integer
            abstract getSeconds: unit -> Integer
            abstract getTime: unit -> Integer
            abstract setHours: hours: Integer -> unit
            abstract setMinutes: minutes: Integer -> unit
            abstract setSeconds: seconds: Integer -> unit
            abstract setTime: milliseconds: Integer -> unit

        and [<AllowNullLiteral>] JdbcTimestamp =
            abstract after: ``when``: JdbcTimestamp -> bool
            abstract before: ``when``: JdbcTimestamp -> bool
            abstract getDate: unit -> Integer
            abstract getHours: unit -> Integer
            abstract getMinutes: unit -> Integer
            abstract getMonth: unit -> Integer
            abstract getNanos: unit -> Integer
            abstract getSeconds: unit -> Integer
            abstract getTime: unit -> Integer
            abstract getYear: unit -> Integer
            abstract setDate: date: Integer -> unit
            abstract setHours: hours: Integer -> unit
            abstract setMinutes: minutes: Integer -> unit
            abstract setMonth: month: Integer -> unit
            abstract setNanos: nanoseconds: Integer -> unit
            abstract setSeconds: seconds: Integer -> unit
            abstract setTime: milliseconds: Integer -> unit
            abstract setYear: year: Integer -> unit

//type [<Erase>]Globals =
//    [<Global>] static member Jdbc with get(): GoogleAppsScript.JDBC.Jdbc = jsNative and set(v: GoogleAppsScript.JDBC.Jdbc): unit = jsNative

